{
 "title": "Iceberg Table Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Records",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "iceberg_snapshot_total_records" }
   ]
  },
  {
   "title": "Total Data Files",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "iceberg_snapshot_total_data_files"
    }
   ]
  },
  {
   "title": "Added Data Files",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "iceberg_snapshot_added_data_files"
    }
   ]
  },
  {
   "title": "Average File Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "iceberg_files_avg_file_size" }
   ]
  }
 ]
}